# Generated by Django 4.1.1 on 2022-09-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(default='', max_length=255)),
                ('Date', models.DateTimeField()),
                ('Venue', models.CharField(default='', max_length=255)),
                ('Link', models.CharField(default='', max_length=255)),
                ('img_url', models.CharField(default='', max_length=255)),
                ('LikedArtists', models.CharField(default='', max_length=255)),
                ('song_url', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
