# Generated by Django 4.1.1 on 2022-09-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(default='', max_length=255)),
                ('Date', models.CharField(default='', max_length=255)),
                ('Link', models.DateTimeField()),
                ('Venue', models.CharField(default='', max_length=255)),
                ('img_url', models.CharField(default='', max_length=255)),
                ('event_day', models.CharField(default='', max_length=255)),
                ('day_mon_year', models.CharField(default='', max_length=255)),
                ('event_day1', models.CharField(default='', max_length=255)),
                ('event_month', models.CharField(default='', max_length=255)),
                ('event_year', models.CharField(default='', max_length=255)),
                ('mon_year', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(default='', max_length=255)),
                ('Date', models.DateTimeField()),
                ('Venue', models.CharField(default='', max_length=255)),
                ('Link', models.CharField(default='', max_length=255)),
                ('img_url', models.CharField(default='', max_length=255)),
                ('event_day', models.CharField(default='', max_length=255)),
                ('day_mon_year', models.CharField(default='', max_length=255)),
                ('event_day1', models.CharField(default='', max_length=255)),
                ('event_month', models.CharField(default='', max_length=255)),
                ('event_year', models.CharField(default='', max_length=255)),
                ('mon_year', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='matches',
            name='LikedArtists',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='song_url',
        ),
        migrations.AddField(
            model_name='matches',
            name='day_mon_year',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matches',
            name='event_day',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matches',
            name='event_day1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matches',
            name='event_month',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matches',
            name='event_year',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matches',
            name='mon_year',
            field=models.CharField(default='', max_length=255),
        ),
    ]
